### ISSUE TITLE
"erreur de syntaxe"

### ISSUE THREAD

**Issue by hsquividant** [geosas/OGC-API-EDR#1]
Testé avec Paul R....
En sélectionnant une zone, le format de sortie NETCDFD4, l'ensemble de la période et plusieurs paramètres, le téléchargement échoue avec le message "erreur de syntaxe" en retour.
Voilà.

**Comment by t-loree** [comment]
C'est corrigé ;) une erreur d'indentation...

**Comment by hsquividant** [comment]
👍
